export const host = "http://localhost:5000"; // https://mylittlecode-api.herokuapp.com
export const registerRoute = `${host}/api/auth/register`
export const loginRoute = `${host}/api/auth/login`
export const setAvatarRoute = `${host}/api/auth/setAvatar`
export const allUsersRoute = `${host}/api/auth/allUsers`
export const getContributedReposRoute = `${host}/api/auth/contributedRepos`
export const sendMessageRoute = `${host}/api/messages/addMessage`
export const gellAllMessagesRoute = `${host}/api/messages/getmgs`
export const getGithubMeRoute = `${host}/api/auth/github/me`
export const getUserImageRoute = `${host}/api/auth/getUserImage`
export const logoutRoute = `${host}/api/auth/logout`
export const getGithubLoginRoute = `${host}/api/auth/github`